#日志配置
logging:
  level:
    root: ${LOGLEVEL:DEBUG}
  file:
    name: cmdb.log

#netty服务配置
netty:
  json:
    port: ${JSONPORT:1024}
  file:
    port: ${FILEPORT:8080}
  # 绑定的网卡
  url: 0.0.0.0

#插件加载目录
classloader:
  plugin:
    path: "D:\\class"

#定时策略
scheduler:
  cron: ${SCHEDULER_CRON:-}  #设置为 -  则关闭定时器
#  cron: "*/10 * * * * *"

#bussiness线程池配置
thredpool:
  coreSize: ${POOL_CORESIZE:1}
  maxSize: ${POOL_MAXSIZE:200}
  queueCapacity: ${POOL_QUEUE:10000}
  threadNamePrefix: "cmdb-thread-"
  isDaemon: false
  nameFormat: "business-pool-%d"
  threadCount: ${BUSSINESS_POOL_COUNT:200}

#数据库连接
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource

# 自定义的主数据源配置信息
primary:
  datasource:
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driverClassName: com.mysql.cj.jdbc.Driver
      #配置基本属性
      url: jdbc:mysql://10.10.49.9:3306/netty?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false
      username: root
      password: 123456
      #配置初始化大小/最小/最大
      initialSize: 1
      minIdle: 1
      maxActive: 20
      #获取连接等待超时时间
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20

# 自定义的从数据源配置信息
back:
  datasource:
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driverClassName: com.mysql.cj.jdbc.Driver
      #配置基本属性
      url: jdbc:mysql://127.0.0.1:3306/idcv?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false
      username: root
      password: 1234
      #配置初始化大小/最小/最大
      initialSize: 1
      minIdle: 1
      maxActive: 20
      #获取连接等待超时时间
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20

