#日志配置
logging:
  level:
    root: ${LOGLEVEL:DEBUG}
  file:
    name: cmdb.log

#netty服务配置
netty:
  json:
    port: ${JSONPORT:1024}
  file:
    port: ${FILEPORT:8080}
  # 绑定的网卡
  url: 0.0.0.0

#bussiness线程池配置
thredpool:
  coreSize: ${POOL_CORESIZE:1}
  maxSize: ${POOL_MAXSIZE:200}
  queueCapacity: ${POOL_QUEUE:10000}
  threadNamePrefix: "cmdb-thread-"

#数据库连接
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource

