logging:
  level:
    root: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    shutdown:
      enabled: true

netty:
  json:
    port: 1024
  file:
    port: 8080
  # 绑定的网卡
  url: 0.0.0.0

thredpool:
  coreSize: 1
  maxSize: 200
  queueCapacity: 10000
  threadNamePrefix: "cmdb-thread-"

