logging:
  level:
    root: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    shutdown:
      enabled: true

netty:
  # 服务端口
  port: 1024
  # 绑定的网卡
  url: 0.0.0.0

